# Generated by Django 4.2.1 on 2023-05-26 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_name", models.CharField(max_length=150)),
                ("cnpj", models.CharField(max_length=20, unique=True)),
                ("corporate_name", models.CharField(max_length=150)),
                ("tel", models.CharField(max_length=20, null=True)),
                ("client_email", models.EmailField(max_length=150, null=True)),
                ("contract_health", models.IntegerField(null=True)),
                ("contract_life", models.IntegerField(null=True)),
                ("contract_dental", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
